---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install vector
  hosts: vector
  roles:
    - vector

- name: Install Nginx
  hosts: lighthouse
  roles:
    - lighthouse

