---
all:
  hosts:
    sonar-01:
      ansible_host: 51.250.94.1
    nexus-01:
      ansible_host: 84.201.174.84
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: test